# These categories will be applied to all DAGs in the repo.
categories:
  - AI + Machine Learning
# List of DAGs that should be published to the Astronomer Registry.
dags:
  - path: dags/train_model
  - path: dags/test_baseline_model
  - path: dags/test_fine_tuned_model